version: '3'
services:
  eft_db:
    container_name: eft_db
    build:
     context: .
     dockerfile: Dockerfile.db
    image: eft_db:latest
    restart: always
    ports:
      - "5433:5432"

  eft_backend:
    container_name: eft_backend
    build: 
     context: .
     dockerfile: Dockerfile
    image: eft_backend:latest
    restart: always 
    ports:
      - 8000:8000
    depends_on:
      - eft_db
    environment:
      DB_CONNECTION_URI: postgres://postgres:0000@eft_db/graduate_fastapi


    
    
