"""default password

Revision ID: 12616a74cb14
Revises: 5484bf8a891b
Create Date: 2023-05-15 16:09:45.250736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12616a74cb14'
down_revision = '5484bf8a891b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
