"""delete picture-transaction

Revision ID: 13c8f392a5f3
Revises: aa7894fd4234
Create Date: 2023-05-08 07:04:20.212854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13c8f392a5f3'
down_revision = 'aa7894fd4234'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pictures', sa.Column('activity_id', sa.Integer(), nullable=True))
    op.drop_constraint('pictures_transact_id_fkey', 'pictures', type_='foreignkey')
    op.drop_constraint('pictures_acticity_id_fkey', 'pictures', type_='foreignkey')
    op.create_foreign_key(None, 'pictures', 'activities', ['activity_id'], ['id'])
    op.drop_column('pictures', 'acticity_id')
    op.drop_column('pictures', 'transact_id')
    op.add_column('transactions', sa.Column('acticity_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transactions', 'activities', ['acticity_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'acticity_id')
    op.add_column('pictures', sa.Column('transact_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pictures', sa.Column('acticity_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'pictures', type_='foreignkey')
    op.create_foreign_key('pictures_acticity_id_fkey', 'pictures', 'activities', ['acticity_id'], ['id'])
    op.create_foreign_key('pictures_transact_id_fkey', 'pictures', 'transactions', ['transact_id'], ['id'])
    op.drop_column('pictures', 'activity_id')
    # ### end Alembic commands ###
