"""book api & transaction table del activity_id

Revision ID: 4ece259f936e
Revises: 9dae4b3b4854
Create Date: 2023-05-17 20:45:41.595052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ece259f936e'
down_revision = '9dae4b3b4854'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('transactions_acticity_id_fkey', 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'acticity_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('acticity_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('transactions_acticity_id_fkey', 'transactions', 'activities', ['acticity_id'], ['id'])
    # ### end Alembic commands ###
