"""user add token

Revision ID: 79f8a35d0c80
Revises: 12616a74cb14
Create Date: 2023-05-17 20:28:09.966602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79f8a35d0c80'
down_revision = '12616a74cb14'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clubs', sa.Column('token', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clubs', 'token')
    # ### end Alembic commands ###
