"""user(token) not null

Revision ID: 9dae4b3b4854
Revises: 79f8a35d0c80
Create Date: 2023-05-17 20:30:05.544167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dae4b3b4854'
down_revision = '79f8a35d0c80'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clubs', 'token',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clubs', 'token',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
