"""first migration

Revision ID: aa7894fd4234
Revises: 
Create Date: 2023-05-08 06:33:25.448022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa7894fd4234'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('club_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'activities', 'clubs', ['club_id'], ['id'])
    op.add_column('booked', sa.Column('transact_id', sa.Integer(), nullable=True))
    op.drop_constraint('booked_tansact_id_fkey', 'booked', type_='foreignkey')
    op.create_foreign_key(None, 'booked', 'transactions', ['transact_id'], ['id'])
    op.drop_column('booked', 'tansact_id')
    op.add_column('pictures', sa.Column('transact_id', sa.Integer(), nullable=True))
    op.drop_constraint('pictures_tansact_id_fkey', 'pictures', type_='foreignkey')
    op.drop_constraint('pictures_club_id_fkey', 'pictures', type_='foreignkey')
    op.create_foreign_key(None, 'pictures', 'transactions', ['transact_id'], ['id'])
    op.drop_column('pictures', 'tansact_id')
    op.drop_column('pictures', 'club_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pictures', sa.Column('club_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pictures', sa.Column('tansact_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'pictures', type_='foreignkey')
    op.create_foreign_key('pictures_club_id_fkey', 'pictures', 'clubs', ['club_id'], ['id'])
    op.create_foreign_key('pictures_tansact_id_fkey', 'pictures', 'transactions', ['tansact_id'], ['id'])
    op.drop_column('pictures', 'transact_id')
    op.add_column('booked', sa.Column('tansact_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'booked', type_='foreignkey')
    op.create_foreign_key('booked_tansact_id_fkey', 'booked', 'transactions', ['tansact_id'], ['id'])
    op.drop_column('booked', 'transact_id')
    op.drop_constraint(None, 'activities', type_='foreignkey')
    op.drop_column('activities', 'club_id')
    # ### end Alembic commands ###
